[build]
builder = "NIXPACKS"
watchPatterns = ["src/**", "package.json"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
NODE_ENV = "production"

[environments.staging]
NODE_ENV = "staging"

