[build]
builder = "NIXPACKS"
watchPatterns = ["src/**", "package.json"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[environments.production]
NODE_ENV = "production"

[environments.staging]
NODE_ENV = "staging"

